# Generated by Django 5.2.8 on 2025-12-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaprestadora',
            name='url_cert_camara_comercio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresaprestadora',
            name='url_rnt_certificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prestadorindividual',
            name='url_permiso_alcaldia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prestadorindividual',
            name='url_rut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
