# Generated by Django 5.2.8 on 2025-12-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardServicioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_card', models.CharField(max_length=150)),
                ('descripcion_corta', models.TextField()),
                ('url_imagen_principal', models.CharField(max_length=255)),
                ('unidad_precio', models.CharField(max_length=50)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('estado_publicacion', models.BooleanField(default=True)),
                ('categoria_servicio', models.CharField(choices=[('GUIA', 'Guia'), ('TRANSPORTE', 'Transporte'), ('AVENTURA', 'Aventura'), ('OTRO', 'Otro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=100)),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('entidad_emisora', models.CharField(max_length=100)),
                ('num_registro', models.CharField(max_length=50, unique=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('url_documento_vigente', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Certificado de Habilidades',
                'verbose_name_plural': 'Certificados de Habilidades',
            },
        ),
        migrations.CreateModel(
            name='RegistroPropina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_propina', models.CharField(choices=[('10%', 'Bajo'), ('20%', 'Medio'), ('30%', 'Alto')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prestadorservicio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicioturistico',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='usuarios',
        ),
        migrations.AlterModelOptions(
            name='turista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='turista',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='numero_pasaporte',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='turista',
            name='contacto_emergencia_nombre',
            field=models.CharField(default='No especificado', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='contacto_emergencia_telefono',
            field=models.CharField(default='No especificado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='idioma_preferido',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turista',
            name='pais_residencia',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_tipo',
            field=models.CharField(choices=[('TURISTA', 'Turista'), ('PRESTADOR', 'Prestador Individual'), ('EMPRESA', 'Empresa')], default='No especificado', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_identificacion',
            field=models.CharField(default='No especificado', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_telefonico',
            field=models.CharField(default='No especificado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(default='No especificado', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='url_foto_documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='turista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_turista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CalificacionServicioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_general', models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], max_length=2)),
                ('feedback_empresa', models.CharField(max_length=50)),
                ('puntuacion_certificados', models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], max_length=2)),
                ('calificacion_puntualidad', models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], max_length=2)),
                ('calificacion_limpieza', models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], max_length=2)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('id_turistas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turista')),
                ('id_card_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardservicioventa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaPrestadora',
            fields=[
                ('nit_empresa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('categoria_empresa', models.CharField(choices=[('Culural', 'A'), ('Natural', 'B'), ('Histórico', 'C'), ('Recreacional', 'D'), ('Gastronómico', 'E'), ('Otros', 'F')], max_length=20)),
                ('rnt_empresa', models.CharField(max_length=50, unique=True)),
                ('url_rnt_certificado', models.CharField(max_length=255)),
                ('matricula_mercantil', models.CharField(max_length=50)),
                ('url_cert_camara_comercio', models.CharField(max_length=255)),
                ('card_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cardservicioventa')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.certificado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_prestadora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('id_certificados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.certificado')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nit_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresaprestadora')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion_servicio_principal', models.CharField(max_length=100)),
                ('estado_afiliacion_seguridad', models.BooleanField(default=False)),
                ('url_rut', models.CharField(max_length=255)),
                ('matricula_comerciante_ind', models.CharField(max_length=50)),
                ('municipio_operacion', models.CharField(max_length=100)),
                ('lugar_prestacion_servicio', models.CharField(max_length=100)),
                ('url_permiso_alcaldia', models.CharField(max_length=255)),
                ('card_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cardservicioventa')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.certificado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestador_individual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cardservicioventa',
            name='id_registro_propina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.registropropina'),
        ),
        migrations.CreateModel(
            name='RegistroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_reporte', models.DateTimeField(blank=True, null=True)),
                ('tipo_reporte', models.CharField(choices=[('QUEJA', 'Queja'), ('RECLAMO', 'Reclamo'), ('DENUNCIA', 'Denuncia')], max_length=20)),
                ('descripcion_detallada', models.TextField()),
                ('url_evidencia_adjunta', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_gestion', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('fecha_cierre_gestion', models.DateTimeField(blank=True, null=True)),
                ('gestion_tomada', models.TextField(blank=True, null=True)),
                ('id_empresas_prestadoras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresaprestadora')),
                ('id_prestador_individual_reportado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prestadorindividual')),
                ('id_turista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.turista')),
            ],
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Interaccion',
        ),
        migrations.DeleteModel(
            name='PrestadorServicio',
        ),
        migrations.DeleteModel(
            name='ServicioTuristico',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
