# Generated by Django 5.2.8 on 2025-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empresaprestadora_url_cert_camara_comercio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaprestadora',
            name='categoria_empresa',
            field=models.CharField(choices=[('Hospedaje', 'Hospedaje'), ('Tours', 'Tours'), ('Guias', 'Guías'), ('Transporte', 'Transporte'), ('Aventura', 'Aventura'), ('Salud', 'Salud'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
