# Generated by Django 5.2.8 on 2025-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_empresaprestadora_categoria_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardservicioventa',
            name='categoria_servicio',
            field=models.CharField(choices=[('HOSPEDAJE', 'Hospedaje'), ('AGENCIAS_TOURS', 'Agencias y Tours'), ('GUIAS', 'Guías'), ('TRANSPORTE', 'Transporte'), ('AVENTURA_RECREACION', 'Aventura y Recreación'), ('SALUD_BIENESTAR', 'Salud y Bienestar'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cardservicioventa',
            name='nombre_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
