# Generated by Django 5.2.8 on 2025-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cardservicioventa_categoria_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionserviciousuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardservicioventa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleadoregistrado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
